# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 527)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mFrame = QtWidgets.QFrame(self.centralwidget)
        self.mFrame.setGeometry(QtCore.QRect(0, 0, 1081, 491))
        self.mFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mFrame.setObjectName("mFrame")
        self.ctLabel = QtWidgets.QLabel(self.mFrame)
        self.ctLabel.setGeometry(QtCore.QRect(20, 10, 231, 16))
        self.ctLabel.setStyleSheet("background-color:#bbbbbb")
        self.ctLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ctLabel.setObjectName("ctLabel")
        self.petLabel = QtWidgets.QLabel(self.mFrame)
        self.petLabel.setGeometry(QtCore.QRect(270, 10, 231, 16))
        self.petLabel.setStyleSheet("background-color:#bbbbbb")
        self.petLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.petLabel.setObjectName("petLabel")
        self.gtSegLabel = QtWidgets.QLabel(self.mFrame)
        self.gtSegLabel.setGeometry(QtCore.QRect(520, 10, 231, 16))
        self.gtSegLabel.setStyleSheet("background-color:#bbbbbb")
        self.gtSegLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gtSegLabel.setObjectName("gtSegLabel")
        self.label_5 = QtWidgets.QLabel(self.mFrame)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 231, 351))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:#aaaaaa")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.petILabel = QtWidgets.QLabel(self.mFrame)
        self.petILabel.setGeometry(QtCore.QRect(270, 30, 231, 351))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.petILabel.setFont(font)
        self.petILabel.setStyleSheet("background-color:#aaaaaa")
        self.petILabel.setAlignment(QtCore.Qt.AlignCenter)
        self.petILabel.setObjectName("petILabel")
        self.gtSegILabel = QtWidgets.QLabel(self.mFrame)
        self.gtSegILabel.setGeometry(QtCore.QRect(520, 30, 231, 351))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gtSegILabel.setFont(font)
        self.gtSegILabel.setStyleSheet("background-color:#aaaaaa")
        self.gtSegILabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gtSegILabel.setObjectName("gtSegILabel")
        self.groupBox = QtWidgets.QGroupBox(self.mFrame)
        self.groupBox.setGeometry(QtCore.QRect(779, 19, 251, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(60, 30, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 54, 16))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(50, 90, 54, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(130, 50, 54, 16))
        self.label_10.setStyleSheet("background-color:#aaaaaa")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(130, 90, 54, 16))
        self.label_11.setStyleSheet("background-color:#aaaaaa")
        self.label_11.setLineWidth(8)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(130, 70, 54, 16))
        self.label_12.setStyleSheet("background-color:#aaaaaa")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(130, 30, 54, 16))
        self.label_13.setStyleSheet("background-color:#aaaaaa")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 251, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(60, 30, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(60, 50, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(50, 70, 54, 16))
        self.label_7.setObjectName("label_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(50, 90, 54, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(130, 50, 54, 16))
        self.label_15.setStyleSheet("background-color:#aaaaaa")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(130, 90, 54, 16))
        self.label_16.setStyleSheet("background-color:#aaaaaa")
        self.label_16.setLineWidth(8)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(130, 70, 54, 16))
        self.label_17.setStyleSheet("background-color:#aaaaaa")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(130, 30, 54, 16))
        self.label_18.setStyleSheet("background-color:#aaaaaa")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.pushButton = QtWidgets.QPushButton(self.mFrame)
        self.pushButton.setGeometry(QtCore.QRect(520, 390, 111, 20))
        self.pushButton.setStyleSheet("background-color:#ee1100")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.mFrame)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 390, 111, 20))
        self.pushButton_2.setStyleSheet("background-color:#11aa00")
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.mFrame)
        self.groupBox_3.setGeometry(QtCore.QRect(780, 160, 251, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(52, 28, 23, 16))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(52, 50, 23, 16))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(70, 50, 31, 16))
        self.label_30.setStyleSheet("background-color:#aaaaaa")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(70, 30, 31, 16))
        self.label_33.setStyleSheet("background-color:#aaaaaa")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setGeometry(QtCore.QRect(70, 70, 31, 16))
        self.label_34.setStyleSheet("background-color:#aaaaaa")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(52, 70, 23, 16))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(155, 70, 31, 16))
        self.label_31.setStyleSheet("background-color:#aaaaaa")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(126, 50, 26, 16))
        self.label_28.setObjectName("label_28")
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(155, 50, 31, 16))
        self.label_36.setStyleSheet("background-color:#aaaaaa")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_3)
        self.label_37.setGeometry(QtCore.QRect(119, 70, 31, 16))
        self.label_37.setObjectName("label_37")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(133, 30, 25, 16))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setGeometry(QtCore.QRect(155, 30, 31, 16))
        self.label_38.setStyleSheet("background-color:#aaaaaa")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ctLabel.setText(_translate("MainWindow", "CT"))
        self.petLabel.setText(_translate("MainWindow", "PET"))
        self.gtSegLabel.setText(_translate("MainWindow", "Segmentation"))
        self.label_5.setText(_translate("MainWindow", "NoImage"))
        self.petILabel.setText(_translate("MainWindow", "NoImage"))
        self.gtSegILabel.setText(_translate("MainWindow", "NoImage"))
        self.groupBox.setTitle(_translate("MainWindow", "患者信息"))
        self.label.setText(_translate("MainWindow", "姓名："))
        self.label_2.setText(_translate("MainWindow", "性别："))
        self.label_3.setText(_translate("MainWindow", "出生年月："))
        self.label_9.setText(_translate("MainWindow", "检查日期："))
        self.groupBox_2.setTitle(_translate("MainWindow", "患者信息"))
        self.label_4.setText(_translate("MainWindow", "姓名："))
        self.label_6.setText(_translate("MainWindow", "性别："))
        self.label_7.setText(_translate("MainWindow", "出生年月："))
        self.label_14.setText(_translate("MainWindow", "检查日期："))
        self.pushButton.setText(_translate("MainWindow", "Ground Truth"))
        self.pushButton_2.setText(_translate("MainWindow", "Segmentation"))
        self.groupBox_3.setTitle(_translate("MainWindow", "坐标信息"))
        self.label_26.setText(_translate("MainWindow", "X："))
        self.label_27.setText(_translate("MainWindow", "Y："))
        self.label_35.setText(_translate("MainWindow", "Z："))
        self.label_28.setText(_translate("MainWindow", "PET："))
        self.label_37.setText(_translate("MainWindow", "Mask："))
        self.label_29.setText(_translate("MainWindow", "CT："))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))

